apiVersion: v1
kind: Service
metadata:
  name: tick-producer
  namespace: trading
  labels:
    app: tick-producer
spec:
  type: ClusterIP
  selector:
    app: tick-producer
  ports:
    - name: actuator
      port: 8081
      targetPort: 8081
